### ISSUE TITLE
immune_to_trap: bad ttype 26

### ISSUE THREAD

**Issue by elunna** [elunna/HACKEM-MUCHE#17]
```
Suddenly, the dungeon collapses.
immune_to_trap: bad ttype 26
  Generating more information you may report:

Program received signal SIGABRT, Aborted.
__pthread_kill_implementation (no_tid=0, signo=6, threadid=140288398469056) at ./nptl/pthread_kill.c:44
44	./nptl/pthread_kill.c: No such file or directory.
(rr) bt
#0  __pthread_kill_implementation (no_tid=0, signo=6, threadid=140288398469056)
    at ./nptl/pthread_kill.c:44
#1  __pthread_kill_internal (signo=6, threadid=140288398469056)
    at ./nptl/pthread_kill.c:78
#2  __GI___pthread_kill (threadid=140288398469056, signo=signo@entry=6)
    at ./nptl/pthread_kill.c:89
#3  0x00007f976fe1a476 in __GI_raise (sig=sig@entry=6)
    at ../sysdeps/posix/raise.c:26
#4  0x00007f976fe007f3 in __GI_abort () at ./stdlib/abort.c:79
#5  0x0000564181d0d7c3 in NH_abort (
    why=0x7ffef39843f0 "immune_to_trap: bad ttype 26") at end.c:212
#6  0x0000564181d105ab in panic (str=0x564182407380 "%s") at end.c:947
#7  0x0000564181fb8c14 in impossible (
    s=0x56418246a940 "immune_to_trap: bad ttype %u") at pline.c:532
#8  0x0000564182148023 in immune_to_trap (mon=0x5641826fd0a8 <gy+8>, ttype=26)
    at trap.c:3293
#9  0x0000564181d66619 in domove_core () at hack.c:2496
#10 0x0000564181d650ac in domove () at hack.c:2374
#11 0x0000564181bd09c7 in rhack (cmd=0x5641826d743c <gc+2332> "8") at cmd.c:5052
#12 0x0000564181b35eb9 in moveloop_core () at allmain.c:520
#13 0x0000564181b36367 in moveloop (resuming=0 '\000') at allmain.c:550
#14 0x0000564182243ba9 in main (argc=2, argv=0x7ffef3985468)
    at ../sys/unix/unixmain.c:310

```

**Comment by elunna** [comment]
Fixed in e67087778
