### ISSUE TITLE
Assert failed after drain life attack

### ISSUE THREAD

**Issue by elunna** [elunna/HACKEM-MUCHE#18]
Something strange picked up by the fuzzer. Looks like a barrow wight hits us with a drain life attack, but somehow we regain the level right away and trigger an assert that checks that the hero should be below level 30. But, the check reveals we are at level 30.

My initial hunch: The barrow wight now has a cold attack *and* we have enabled potion vapor effects. As a result, it is could be that a potion of gain level or restore ability is held by us, broken by the wight's cold attack, we inhale vapors, and we gain the level right after the drain life attack. I'm not sure this makes sense though, the cold attack is last in the wights attacks and the assert is right after the drain life occurs. We were not wearing any rings (if a ring of sustain ability was somehow involved).

Another possibility is being polymorphed into a monster with a powerful passive, like a spotted jelly, which could kill the barrow wight passively after being drain lifed. However, that still doesn't explain how our level would just not be drained after going into the loseexp function...

```
 MON("barrow wight", S_WRAITH, LVL(3, 12, 5, 5, -3),
        (G_GENO | G_NOCORPSE | 1),
        A(ATTK(AT_WEAP, AD_DRLI, 0, 0), ATTK(AT_MAGC, AD_SPEL, 0, 0),
          ATTK(AT_CLAW, AD_PHYS, 1, 4), ATTK(AT_TUCH, AD_COLD, 1, 4),
          NO_ATTK, NO_ATTK),
        SIZ(1200, 0, MS_SPELL, MZ_HUMAN), MR_COLD | MR_SLEEP | MR_POISON, 0,
        M1_BREATHLESS | M1_HUMANOID,
        M2_UNDEAD | M2_STALK | M2_HOSTILE | M2_COLLECT, 0, 8, CLR_GRAY,
        BARROW_WIGHT),
```

```
#0  __pthread_kill_implementation (no_tid=0, signo=6, threadid=140737339570112)
    at ./nptl/pthread_kill.c:44
#1  __pthread_kill_internal (signo=6, threadid=140737339570112)
    at ./nptl/pthread_kill.c:78
#2  __GI___pthread_kill (threadid=140737339570112, signo=signo@entry=6)
    at ./nptl/pthread_kill.c:89
#3  0x00007ffff7282476 in __GI_raise (sig=sig@entry=6)
    at ../sysdeps/posix/raise.c:26
#4  0x00007ffff72687f3 in __GI_abort () at ./stdlib/abort.c:79
#5  0x00007ffff726871b in __assert_fail_base (
    fmt=0x7ffff741d130 "%s%s%s:%u: %s%sAssertion `%s' failed.\n%n", 
    assertion=0x555555f9f2e0 "u.ulevel >= 0 && u.ulevel < MAXULEV", 
    file=0x555555f9f2a0 "exper.c", line=243, function=<optimized out>)
    at ./assert/assert.c:92
#6  0x00007ffff7279e96 in __GI___assert_fail (
    assertion=0x555555f9f2e0 "u.ulevel >= 0 && u.ulevel < MAXULEV", 
    file=0x555555f9f2a0 "exper.c", line=243, 
    function=0x555555f9f4e0 <__PRETTY_FUNCTION__.0> "losexp")
    at ./assert/assert.c:101
#7  0x0000555555962132 in losexp (drainer=0x5555560b0d40 "life drainage")
    at exper.c:243
#8  0x0000555555dc4f80 in mhitm_ad_drli (magr=0x6110007eeb80, 
    mattk=0x555556340da4 <mons+24324>, mdef=0x5555563370a8 <gy+8>, 
    mhm=0x7fffffffdc10) at uhitm.c:2547
#9  0x0000555555dda42f in mhitm_adtyping (magr=0x6110007eeb80, 
    mattk=0x555556340da4 <mons+24324>, mdef=0x5555563370a8 <gy+8>, 
    mhm=0x7fffffffdc10) at uhitm.c:5080
#10 0x0000555555a4d0be in hitmu (mtmp=0x7312e, mattk=0x555556340da4 <mons+24324>)
    at mhitu.c:1313
#11 0x0000555555a4a99f in mattacku (mtmp=0x6110007eeb80) at mhitu.c:1029
#12 0x0000555555aebf61 in dochug (mtmp=0x6110007eeb80) at monmove.c:894
#13 0x0000555555ae4ec9 in dochugw (mtmp=0x6110007eeb80, chug=1 '\001')
    at monmove.c:194
#14 0x0000555555ab196b in movemon_singlemon (mtmp=0x6110007eeb80) at mon.c:1151
#15 0x0000555555ace6d1 in iter_mons_safe (
    func=0x555555ab0a4c <movemon_singlemon>) at mon.c:4336
#16 0x0000555555ab19c7 in movemon () at mon.c:1161
#17 0x000055555576dbb8 in moveloop_core () at allmain.c:194
#18 0x0000555555770367 in moveloop (resuming=0 '\000') at allmain.c:550
#19 0x0000555555e7dba9 in main (argc=4, argv=0x7fffffffe4a8)
    at ../sys/unix/unixmain.c:310

(gdb) p gm.moves
$1 = 2456612

(gdb) p u.ulevel
$2 = 30

(gdb) p gt.toplines
$5 = "Welcome back to experience level 30.", '\000' <repeats 263 times>


monster hitting us: Barrow wight
(gdb) p *magr
$4 = {nmon = 0x0, data = 0x555556340d80 <mons+24288>, m_id = 3174753, 
  mnum = 253, cham = -1, movement = 0, m_lev = 4 '\004', malign = 0 '\000', 
  mx = 38, my = 4, mux = 39, muy = 4, mtrack = {{x = 39, y = 4}, {x = 39, 
      y = 5}, {x = 38, y = 6}, {x = 37, y = 5}}, mhp = 15, mhpmax = 25, 
  mappearance = 0, m_ap_type = 0 '\000', mtame = 0 '\000', mintrinsics = 0, 
  mextrinsics = 0, seen_resistance = 0, mspec_used = 5, female = 1, minvis = 0, 
  invis_blkd = 0, perminvis = 0, mcan = 0, mburied = 0, mundetected = 0, 
  mcansee = 1, mspeed = 2, permspeed = 2, mrevived = 0, mcloned = 0, 
  mavenge = 0, mflee = 0, mfleetim = 0, msleeping = 0, mblinded = 0, mstun = 0, 
  mfrozen = 0, mcanmove = 1, mconf = 0, mpeaceful = 0, mtrapped = 0, 
  mleashed = 0, isshk = 0, isminion = 0, isgd = 0, ispriest = 0, iswiz = 0, 
  wormno = 0, mtemplit = 0, meverseen = 1, mwither_from_u = 0, mberserk = 0, 
  mwither = 0 '\000', mstrategy = 0, mtrapseen = 0, mlstmv = 2456472, 
  mstate = 0, migflags = 0, mspare1 = 0, minvent = 0x60b000b41ee0, 
  mw = 0x60b0004f94f0, misc_worn_check = 536870912, weapon_check = 1, 
  former_rank = '\000' <repeats 24 times>, meating = 0, mreflecttime = 0, 
  mprotection = 0 '\000', mprottime = 0 '\000', mextra = 0x0}
(gdb) 

Our youmonst:
(gdb) p gy.youmonst
$6 = {nmon = 0x0, data = 0x5555563437e0 <mons+35136>, m_id = 0, mnum = 366, 
  cham = -1, movement = 0, m_lev = 0 '\000', malign = 0 '\000', mx = 0, my = 0, 
  mux = 0, muy = 0, mtrack = {{x = 0, y = 0}, {x = 0, y = 0}, {x = 0, y = 0}, {
      x = 0, y = 0}}, mhp = 0, mhpmax = 0, mappearance = 0, 
  m_ap_type = 0 '\000', mtame = 0 '\000', mintrinsics = 0, mextrinsics = 0, 
  seen_resistance = 0, mspec_used = 0, female = 0, minvis = 0, invis_blkd = 0, 
  perminvis = 0, mcan = 0, mburied = 0, mundetected = 0, mcansee = 0, 
  mspeed = 0, permspeed = 0, mrevived = 0, mcloned = 0, mavenge = 0, mflee = 0, 
  mfleetim = 0, msleeping = 0, mblinded = 0, mstun = 0, mfrozen = 0, 
  mcanmove = 0, mconf = 0, mpeaceful = 0, mtrapped = 0, mleashed = 0, isshk = 0, 
  isminion = 0, isgd = 0, ispriest = 0, iswiz = 0, wormno = 0, mtemplit = 0, 
  meverseen = 0, mwither_from_u = 0, mberserk = 0, mwither = 0 '\000', 
  mstrategy = 0, mtrapseen = 0, mlstmv = 0, mstate = 0, migflags = 0, 
  mspare1 = 0, minvent = 0x0, mw = 0x0, misc_worn_check = 0, weapon_check = 0, 
  former_rank = '\000' <repeats 24 times>, meating = 0, mreflecttime = 0, 
  mprotection = 0 '\000', mprottime = 0 '\000', mextra = 0x0}


(gdb) p u.umonster
$7 = 366 (ranger)
(gdb) p u.umonnum
$8 = 366

```

**Comment by elunna** [comment]
Fixed in https://github.com/NetHack/NetHack/commit/90d515b6ab6edb0f0945bd932ed2192357b4164e
