### ISSUE TITLE
ceiling hider hiding in solid stone (fmon) [GREEN SLIME]

### ISSUE THREAD

**Issue by elunna** [elunna/HACKEM-MUCHE#20]
This is related to 45c6a5ca4, which enables green slimes to hide on the ceiling. I ported this from xNetHack, but searching their repo didn't reveal any fixes for this issue. 

```
Suddenly, the dungeon collapses.
ceiling hider hiding in solid stone (fmon)
  Generating more information you may report:

#0  __pthread_kill_implementation (no_tid=0, signo=6, threadid=140706088187840)
    at ./nptl/pthread_kill.c:44
#1  __pthread_kill_internal (signo=6, threadid=140706088187840)
    at ./nptl/pthread_kill.c:78
#2  __GI___pthread_kill (threadid=140706088187840, signo=signo@entry=6)
    at ./nptl/pthread_kill.c:89
#3  0x00007ff8b021a476 in __GI_raise (sig=sig@entry=6)
    at ../sysdeps/posix/raise.c:26
#4  0x00007ff8b02007f3 in __GI_abort () at ./stdlib/abort.c:79
#5  0x000055bb610df7c3 in NH_abort (
    why=0x7ffe8ceba740 "ceiling hider hiding in solid stone (fmon)") at end.c:212
#6  0x000055bb610e25ab in panic (str=0x55bb617d83c0 "%s") at end.c:947
#7  0x000055bb6138a905 in impossible (
    s=0x55bb61778ec0 "ceiling hider hiding %s (%s)") at pline.c:532
#8  0x000055bb61242299 in sanity_check_single_mon (mtmp=0x61100011d540, 
    chk_geno=1 '\001', msg=0x55bb61779260 "fmon") at mon.c:168
#9  0x000055bb61242746 in mon_sanity_check () at mon.c:222
#10 0x000055bb60f9df2a in sanity_check () at cmd.c:4284
#11 0x000055bb60f05ad9 in moveloop_core () at allmain.c:183
#12 0x000055bb60f08367 in moveloop (resuming=0 '\000') at allmain.c:550
#13 0x000055bb616158f2 in main (argc=2, argv=0x7ffe8cebb4d8)

(rr) p gm.moves
$1 = 948949
```

Monster is a green slime
```
(rr) p *mtmp
$2 = {nmon = 0x6110005c3e00, data = 0x55bb61ad7520 <mons+22080>, m_id = 1509987, 
  mnum = 230, cham = -1, movement = 0, m_lev = 5 '\005', malign = 5 '\005', 
  mx = 12, my = 6, mux = 68, muy = 9, mtrack = {{x = 0, y = 0}, {x = 0, y = 0}, {
      x = 0, y = 0}, {x = 0, y = 0}}, mhp = 16, mhpmax = 16, mappearance = 0, 
  m_ap_type = 0 '\000', mtame = 0 '\000', mintrinsics = 0, mextrinsics = 0, 
  seen_resistance = 0, mspec_used = 0, female = 0, minvis = 0, invis_blkd = 0, 
  perminvis = 0, mcan = 0, mburied = 0, mundetected = 1, mcansee = 1, 
  mspeed = 0, permspeed = 0, mrevived = 0, mcloned = 0, mavenge = 0, mflee = 0, 
  mfleetim = 0, msleeping = 0, mblinded = 0, mstun = 0, mfrozen = 0, 
  mcanmove = 1, mconf = 0, mpeaceful = 0, mtrapped = 0, mleashed = 0, isshk = 0, 
  isminion = 0, isgd = 0, ispriest = 0, iswiz = 0, wormno = 0, mtemplit = 0, 
  meverseen = 0, mwither_from_u = 0, mberserk = 0, mwither = 0 '\000', 
  mstrategy = 0, mtrapseen = 0, mlstmv = 0, mstate = 0, migflags = 0, 
  mspare1 = 0, minvent = 0x0, mw = 0x0, misc_worn_check = 0, weapon_check = 0, 
  former_rank = '\000' <repeats 24 times>, meating = 0, mreflecttime = 0, 
  mprotection = 0 '\000', mprottime = 0 '\000', mextra = 0x0}

    mundetected = 1
    
    mx = 12, my = 6,
    
(rr) p gl.level.locations[12][6].typ
$3 = 23 '\027' DOOR
```
From following the mundetected flag, the green slime was created from a wizwish and hidden on creation. Oddly, it was also able to hide on the ceiling on a door.

```
(rr) p gm.moves
$7 = 948949
(rr) bt
#0  0x000055bb613eff1d in create_particular_creation (d=0x7ffe8cebaac0)
    at read.c:3138
#1  0x000055bb613f0c3c in create_particular_from_buffer (
    bufp=0x7ffe8cebace0 "07771P") at read.c:3222
#2  0x000055bb61613a4f in makewish () at zap.c:6367
#3  0x000055bb60f888dc in wiz_wish () at cmd.c:1010
#4  0x000055bb60fa26fe in rhack (cmd=0x55bb61aa847c <gc+2332> "\027")
    at cmd.c:5011
#5  0x000055bb60f07eb9 in moveloop_core () at allmain.c:520
#6  0x000055bb60f08367 in moveloop (resuming=0 '\000') at allmain.c:550
#7  0x000055bb616158f2 in main (argc=2, argv=0x7ffe8cebb4d8)
```

If we look into the space where the green slime is hiding, the location flags is set to 4, which I believe is a closed door. So I think that is where the bug lies. The mystery is why a green slime ran into this problem, but not lurkers above. It is probably because they are amorphous, so they can ooze under doors, resulting in the monster generator considering doors a valid place for them to generate hidden.
```
(rr) p gl.level.locations[12][6]
$12 = {glyph = 11067, typ = 23 '\027', seenv = 0 '\000', flags = 4, 
  horizontal = 0, lit = 1, waslit = 0, roomno = 4, edge = 1, candig = 0}
```

**Comment by elunna** [comment]
Easy to reproduce, wish for a green slime next to a closed door until one spawns in and triggers the panic.
