### ISSUE TITLE
strange weapon type 42 for hit message

### ISSUE THREAD

**Issue by elunna** [elunna/HACKEM-MUCHE#6]
```
Suddenly, the dungeon collapses.
strange weapon type 42 for hit message
  Generating more information you may report:

Program received signal SIGABRT, Aborted.
__GI_raise (sig=sig@entry=6) at ../sysdeps/unix/sysv/linux/raise.c:50
50      ../sysdeps/unix/sysv/linux/raise.c: No such file or directory.
(gdb) bt
#0  __GI_raise (sig=sig@entry=6) at ../sysdeps/unix/sysv/linux/raise.c:50
#1  0x00007ffff71fa859 in __GI_abort () at abort.c:79
#2  0x0000555555937bc4 in NH_abort (why=0x7fffffffd0d0 "strange weapon type 42 for hit message")
    at end.c:212
#3  0x000055555593a8f5 in panic (str=0x555556012e20 "%s") at end.c:946
#4  0x0000555555bd7144 in impossible (s=0x555555fa5f20 "strange weapon type %d for hit message")
    at pline.c:532
#5  0x0000555555a2bfc0 in weaphitmsg (weap=0x60b00057f3e0, magr=0x6110006cd800) at mhitu.c:90
#6  0x0000555555a2d1dd in hitmsg (mtmp=0x6110006cd800, mattk=0x5555563213a4 <mons+14340>)
    at mhitu.c:214
#7  0x0000555555dae8ac in mhitm_ad_phys (magr=0x6110006cd800, mattk=0x5555563213a4 <mons+14340>,
    mdef=0x555556302ba8 <gy+8>, mhm=0x7fffffffddb0) at uhitm.c:4232
#8  0x0000555555db46db in mhitm_adtyping (magr=0x6110006cd800,
    mattk=0x5555563213a4 <mons+14340>, mdef=0x555556302ba8 <gy+8>, mhm=0x7fffffffddb0)
    at uhitm.c:4983
#9  0x0000555555a37c45 in hitmu (mtmp=0x2, mattk=0x5555563213a4 <mons+14340>) at mhitu.c:1313
#10 0x0000555555a35552 in mattacku (mtmp=0x6110006cd800) at mhitu.c:1029
#11 0x0000555555ad4a08 in dochug (mtmp=0x6110006cd800) at monmove.c:892
#12 0x0000555555acdac2 in dochugw (mtmp=0x6110006cd800, chug=1 '\001') at monmove.c:194
#13 0x0000555555a9b261 in movemon_singlemon (mtmp=0x6110006cd800) at mon.c:1151
#14 0x0000555555ab7b7e in iter_mons_safe (func=0x555555a9a33f <movemon_singlemon>) at mon.c:4325
#15 0x0000555555a9b2ba in movemon () at mon.c:1161
#16 0x0000555555762b7f in moveloop_core () at allmain.c:195
--Type <RET> for more, q to quit, c to continue without paging--up
#17 0x0000555555765406 in moveloop (resuming=0 '\000') at allmain.c:574
#18 0x0000555555e572de in main (argc=4, argv=0x7fffffffe628) at ../sys/unix/unixmain.c:310
```

**Comment by elunna** [comment]
Attacker: forest centaur
(gdb) p *magr
$1 = {nmon = 0x0, data = 0x555556321380 <mons+14304>, m_id = 69756, mnum = 149, cham = -1,
  movement = 0, m_lev = 6 '\006', malign = 3 '\003', mx = 60, my = 7, mux = 61, muy = 6,
  mtrack = {{x = 59, y = 8}, {x = 58, y = 9}, {x = 57, y = 9}, {x = 58, y = 8}}, mhp = 30,
  mhpmax = 30, mappearance = 0, m_ap_type = 0 '\000', mtame = 0 '\000', mintrinsics = 0,
  mextrinsics = 0, seen_resistance = 0, mspec_used = 0, female = 1, minvis = 0, invis_blkd = 0,
  perminvis = 0, mcan = 0, mburied = 0, mundetected = 0, mcansee = 1, mspeed = 0, permspeed = 0,
  mrevived = 0, mcloned = 0, mavenge = 0, mflee = 0, mfleetim = 0, msleeping = 0, mblinded = 0,
  mstun = 0, mfrozen = 0, mcanmove = 1, mconf = 0, mpeaceful = 0, mtrapped = 0, mleashed = 0,
  isshk = 0, isminion = 0, isgd = 0, ispriest = 0, iswiz = 0, wormno = 0, mtemplit = 0,
  meverseen = 0, mwither_from_u = 0, mberserk = 0, mwither = 0 '\000', mstrategy = 0,
  mtrapseen = 0, mlstmv = 0, mstate = 0, migflags = 0, mspare1 = 0, minvent = 0x60b00057f3e0,
  mw = 0x60b00057f3e0, misc_worn_check = 536870912, weapon_check = 1,
  former_rank = '\000' <repeats 24 times>, meating = 0, mreflecttime = 0,
  mprotection = 0 '\000', mprottime = 0 '\000', mextra = 0x0}


Defender: monk
(gdb) p *mdef
$3 = {nmon = 0x0, data = 0x5555563263c0 <mons+34848>, m_id = 0, mnum = 363, cham = -1,
  movement = 0, m_lev = 0 '\000', malign = 0 '\000', mx = 0, my = 0, mux = 0, muy = 0, mtrack = {
    {x = 0, y = 0}, {x = 0, y = 0}, {x = 0, y = 0}, {x = 0, y = 0}}, mhp = 0, mhpmax = 0,
  mappearance = 0, m_ap_type = 0 '\000', mtame = 0 '\000', mintrinsics = 0, mextrinsics = 0,
  seen_resistance = 0, mspec_used = 0, female = 0, minvis = 0, invis_blkd = 0, perminvis = 0,
  mcan = 0, mburied = 0, mundetected = 0, mcansee = 0, mspeed = 0, permspeed = 0, mrevived = 0,
  mcloned = 0, mavenge = 0, mflee = 0, mfleetim = 0, msleeping = 0, mblinded = 0, mstun = 0,
  mfrozen = 0, mcanmove = 0, mconf = 0, mpeaceful = 0, mtrapped = 0, mleashed = 0, isshk = 0,
  isminion = 0, isgd = 0, ispriest = 0, iswiz = 0, wormno = 0, mtemplit = 0, meverseen = 0,
  mwither_from_u = 0, mberserk = 0, mwither = 0 '\000', mstrategy = 0, mtrapseen = 0,
  mlstmv = 0, mstate = 0, migflags = 0, mspare1 = 0, minvent = 0x0, mw = 0x0,
  misc_worn_check = 0, weapon_check = 0, former_rank = '\000' <repeats 24 times>, meating = 0,
  mreflecttime = 0, mprotection = 0 '\000', mprottime = 0 '\000', mextra = 0x0}


The problem is probably actually the weapon involved:
(gdb) p *weap
$4 = {nobj = 0x60b00057ee60, v = {v_nexthere = 0x6110006cd800, v_ocontainer = 0x6110006cd800,
    v_ocarry = 0x6110006cd800}, cobj = 0x0, o_id = 69773, ox = 60, oy = 7, otyp = 42, owt = 20,
  quan = 1, spe = 0 '\000', oclass = 2 '\002', invlet = 0 '\000', oartifact = 0 '\000',
  where = 4 '\004', timed = 0, cursed = 0, blessed = 0, unpaid = 0, no_charge = 0, known = 0,
  dknown = 0, bknown = 0, rknown = 0, oeroded = 0, oeroded2 = 0, oerodeproof = 0, olocked = 0,
  obroken = 0, otrapped = 0, recharged = 0, lamplit = 0, globby = 0, greased = 0, nomerge = 0,
  how_lost = 0, in_use = 0, bypass = 0, cknown = 0, lknown = 0, pickup_prev = 0, ghostly = 0,
  corpsenm = -1, usecount = 0, oeaten = 0, age = 18080, owornmask = 256, lua_ref_cnt = 0,
  omigr_from_dnum = 0, omigr_from_dlevel = 0, oextra = 0x0}

This is a worm tooth, which doesn't have an oc_dir defined.
